### ISSUE TITLE
Adding SCHEMA_VERSION and BIDS_VERSION files

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-schema#5]
Just asking for confirmation before I make a PR.

Particularly the `SCHEMA_VERSION` would be just to provide homogeneous input, i.e. validators could prospectively check and see that they don't support the version (none of the current releases support even the prospective `0.3.*` series) — instead of having a special case where a missing file means not an incomplete schema but an older version. So I was thinking of adding `0.1.0` for all historical versions up to `1.7.0`.

Additionally, something we didn't get to discussing on friday, is whether `BIDS_VERSION`s would have fixed `SCHEMA_VERSION`s. Conceptually they don't need to, but if we try to implement that here we'd need to come up with a way of organizing directories to account for that.

What I assumed [here](https://github.com/bids-standard/bids-specification/issues/1144#issuecomment-1201861043) was that we in practice use one-to-one, and I think what was seen in the drawing from the office whiteboard is that *at most* there should be a many-to-one correspondence between `BIDS_VERSION` and `SCHEMA_VERSION` right now, and we only work on many-to-many (i.e. aforementioned subdirectory reorganization of the form `bids-schema-1.7.0/schema-0.3.0/..`) unless somebody very seriously needs this.

@yarikoptic

**Comment by yarikoptic** [comment]
> So I was thinking of adding `0.1.0` for all historical versions up to `1.7.0`.

make it `0.0.1`, i.e. as it was `0.0` series.  We had assigned it 0.1.0 in http://github.com/bids-standard/bids-specification/commit/1379ab0c51ffb0bc06a333be4939b79791bd6734 which  was v1.7.0-54-g1379ab0c already.

>  is whether BIDS_VERSIONs would have fixed SCHEMA_VERSIONs.... (i.e. aforementioned subdirectory reorganization of the form bids-schema-1.7.0/schema-0.3.0/..)

I feel like we (or I by myself) also had this idea at some point. So "great mind think alike" . I think I would not bother.  If we ever need (and become able) to upgrade some older releases of bids to new schema, we would just do that *in place) and their SCHEMA_VERSION would reflect that.  Then we would have releases of this repo itself (let's talk about versioning ;)), so if someone needs to live in the past, they should be able to get prior release/version with older SCHEMA_VERSION versions.
