### ISSUE TITLE
Shouldn’t versions/latest match versions/1.10.0?

### ISSUE THREAD

**Issue by musicinmybrain** [bids-standard/bids-schema#9]
Currently, in 90cd4cb494ff36a76dbf97d2d0deab4f970b17c5, we have `versions/1.10.0`, but `versions/latest` corresponds to `versions/1.9.0`. Is that an oversight? Am I missing anything?

**Comment by yarikoptic** [comment]
THANK YOU for the report... it is not yet fully automated, let me try to cook up a quick CI workflow for this...

**Comment by musicinmybrain** [comment]
Thanks for investigating!

**Comment by yarikoptic** [comment]
actually I originally misunderstood the concern here, now fixed properly in code in
- 0c4ec20522919bbf4e474e9d37dbd1b53dd2d102
and then 6214096f04e657649f0c1a57088a1c862fe7a02d to actually get that copy... testing automated cron job now to get master updated automagically etc...
